work on adaptivity (70%)
danil-react/First-add pull request #6
Opened 2020-11-16 15:29 UTC by danil-react

work on adaptivity

2020-11-16 20:15 UTC, justiceteam-it requested changes
please fix it. after merge

2020-11-16 20:15 UTC, justiceteam-it commented on src/components/Card/styles.module.scss
> +  margin-left: 50px;
margin: 0 50px;

2020-11-16 20:15 UTC, justiceteam-it commented on src/components/Card/styles.module.scss
> +    margin-left: 1px;
margin:0 1px;

2020-11-16 20:15 UTC, justiceteam-it commented on src/components/Card/styles.module.scss
> +  }
same

2020-11-16 20:15 UTC, justiceteam-it commented on src/components/Navbar/Navbar.js
> +          <Nav className="1111">
what is it?

2020-11-16 20:15 UTC, justiceteam-it commented on src/components/Navbar/Navbar.js
> +    // </div>
remove

2020-11-16 20:15 UTC, justiceteam-it commented on src/layouts/Cart/styles.module.scss
> +  margin: 50px!important;
don't use

2020-11-16 20:15 UTC, justiceteam-it commented on src/layouts/SignIn/index.js
> +                                    <Button variant="primary" className={styles.SignUpButton} type="submit">
lower case

2020-11-16 20:15 UTC, justiceteam-it commented on src/layouts/SignUp/index.js
> +                            <h1 className={styles.SignInHeading}>Create an account</h1>
same

2020-11-16 20:15 UTC, justiceteam-it commented on src/layouts/SignUp/index.js
> +                                    <Button className={styles.SignUpButton} type="submit">
same

2020-11-16 20:15 UTC, justiceteam-it commented on src/styles.module.scss
> +  width: 1800px!important;
don't use

2020-11-17 07:45 UTC, danil-react commented on src/components/Navbar/Navbar.js
> +          <Nav className="1111">
this is test class, i removed it

2020-11-17 07:49 UTC, merged